[package]
name = "Skill-Disarmament"
description = ""
homepage = ""
repository = "https://github.com/CAEZAR-SCARLET-RAGNAROK/Skill-Disarmament"
authors = [ "Caezar",]
version = "0.19.4"

[tools.mwse]
lua-mod = "Caezar.Skill-Disarmament"

[dependencies.mods."Skills Module"]
mwse-module = "OtherSkills"
url = "https://www.nexusmods.com/morrowind/mods/46034?tab=files"
